CREATE SCHEMA hit;

CREATE TABLE hit.items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    category VARCHAR(100) NOT NULL,
    location VARCHAR(100) NOT NULL,
    quantity INTEGER NOT NULL
        CONSTRAINT quantity_non_negative CHECK (quantity >= 0),
    minimum_quantity INTEGER NOT NULL
        CONSTRAINT minimum_quantity_non_negative CHECK (minimum_quantity >= 0),
    notes TEXT NOT NULL DEFAULT ''
);
