CREATE SCHEMA IF NOT EXISTS hit;

CREATE TABLE IF NOT EXISTS hit.items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    category VARCHAR(100) NOT NULL,
    location VARCHAR(100) NOT NULL,
    tracking_mode VARCHAR(20) NOT NULL DEFAULT 'quantity'
        CONSTRAINT tracking_mode_allowed
        CHECK (tracking_mode IN ('quantity', 'individual')),
    quantity INTEGER
        CONSTRAINT quantity_non_negative CHECK (quantity >= 0),
    minimum_quantity INTEGER
        CONSTRAINT minimum_quantity_non_negative CHECK (minimum_quantity >= 0),
    notes TEXT NOT NULL DEFAULT '',
    CONSTRAINT tracking_mode_quantity_fields
    CHECK (
        (
            tracking_mode = 'quantity'
            AND quantity IS NOT NULL
            AND minimum_quantity IS NOT NULL
        )
        OR
        (
            tracking_mode = 'individual'
            AND quantity IS NULL
            AND minimum_quantity IS NULL
        )
    )
);
